project:
  type: website
  output-dir: docs

website:
  title: "Notes on Light"
  search: true
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Archive"
        menu:
          - text: "Atmospheric Optics"
            href: posts/sky-blue/index.qmd
          - text: "Fiber Optics"
            href: posts/fiber-optics/index.qmd
  # Add this section below
  page-footer:
    background: light
    left: "Â© 2026 Stories of Light"
    right: 
      - icon: envelope
        text: Email
        href: mailto:isuruwithanawasam98@example.com
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/isuru-withanawasam-11b237195/
      - icon: globe
        text: Portfolio
        href: https://isuruwithanawasam.github.io/

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true